services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_db
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - '${MINIO_API_PORT}:${MINIO_API_PORT}'
      - '${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '${MAILHOG_SMTP_PORT}:${MAILHOG_SMTP_PORT}'
      - '${MAILHOG_WEB_PORT}:${MAILHOG_WEB_PORT}'

  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - '${ELASTICMQ_PORT}:${ELASTICMQ_PORT}'
    volumes:
      - elasticmq_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data:
  elasticmq_data: