services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - ./docker/redis:/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - '${MINIO_API_PORT}:${MINIO_API_PORT}' # Minio API
      - '${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}' # Minio Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio:/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '${MAILHOG_SMTP_PORT}:${MAILHOG_SMTP_PORT}' # SMTP server
      - '${MAILHOG_WEB_PORT}:${MAILHOG_WEB_PORT}' # Web interface

  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - '${ELASTICMQ_PORT}:${ELASTICMQ_PORT}'
    environment:
      JAVA_OPTS: "-Dconfig.file=/opt/elasticmq.conf"
    volumes:
      - ./docker/elasticmq:/data